language: cpp

matrix:
  include:
    - os: osx
    # Linux quality assurance job
    - os: linux
      addons:
        apt:
          packages: lcov
        sonarcloud:
          organization: "maciejzj"
          token:
            secure: "auwXhWVBKhP8kxA251P/dW16Nyuu/7I+0Fk2F7WuNNkkNDD/h5yrhe+zsxKoocOhMjWqV4yzxKwr0xtt5EIoBouAezkT5G+dYXe2Sc9r820lBOmt3LYLIdPTqojbl3xyzJoo6wfiL0UKLDnB1dBa/CGCzCmZm/ipYAzGxLKZsH5yjEuqjdUkxURTOI/R3Ptdh6uesoYn5YMVckRQjy8rIGQ1EuMBL+18gUIgNYudj4Y4NGpPrgXCxjR2b0BAA40cR9t0djiHoJ2AxejHL51scr7w//lWNaGPhtfr3tPs2j/CcQ+YKuu9ecKjYzMVFGimJ5NkXgEsl1zslg46+bCDJPWNtkdvuN3jnsf9cjr+O3JPlDAxX6CnZubjrDLRxJcEcWibrF3XtoBHMt7P0nMDqCnDHmbCJZFS1X/X00pz0Ma8yEvH9XdNUkighnzfc0qKg+ybgVI+O6NtOxAGvPh6fWsMS6SjmJlrvK60QHaNziCcFCoUTOZyMmXwcjwNYusPVIirONDobbbmgid2FzXUpGwOsH+m+AmbLDyKj75RGNUysF+VEmJWk+Pr9ZSspmJJBB9ER7x8kzqBJHd9brSZJuLmqjjx89TOf2z484AZnTPWVcXJBkA7NPFne6nHuLV0Dy4s5AY519aBJF9ND0KIZMxDrsKzDtrqWFa+/vRZan4=" # encrypted value of token
      env:
        - ENABLE_COVERAGE=ON
        - SONAR_BUILD_WRAPPER="build-wrapper-linux-x86-64 --out-dir bw-output"

before_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=${ENABLE_COVERAGE} ..

script:
  - make clean
  # The wrapper is required by Sonar Cloud
  - ${BUILD_WRAPPER} make -j2
  - ctest -j2

after_success:
  # Lcov coverage for Codecov
  # To not include test code in coverage add them to the patterns: '*/tests/*'
  - >
    sh -c "[ -n "${ENABLE_COVERAGE}" ] &&
    lcov --capture --directory . --output-file coverage.info &&
    lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*'
    --output-file coverage.info &&
    bash <(curl -s https://codecov.io/bash) -t
    06fa5b08-3be1-480a-9af4-ffcec2672fa1 -f coverage.info ||
    echo "Codecov did not collect coverage reports""
  - >
    sh -c "[ -n "${SONAR_BUILD_WRAPPER}" ] &&
    cd .. &&
    sonar-scanner -Dproject.settings=.sonarcloud.properties"

