language: cpp
os: linux

complier:
  - gcc
  - clang

addons:
  apt:
    packages: lcov
  sonarcloud:
    organization: "maciejzj"
    token:
      secure: "auwXhWVBKhP8kxA251P/dW16Nyuu/7I+0Fk2F7WuNNkkNDD/h5yrhe+zsxKoocOhMjWqV4yzxKwr0xtt5EIoBouAezkT5G+dYXe2Sc9r820lBOmt3LYLIdPTqojbl3xyzJoo6wfiL0UKLDnB1dBa/CGCzCmZm/ipYAzGxLKZsH5yjEuqjdUkxURTOI/R3Ptdh6uesoYn5YMVckRQjy8rIGQ1EuMBL+18gUIgNYudj4Y4NGpPrgXCxjR2b0BAA40cR9t0djiHoJ2AxejHL51scr7w//lWNaGPhtfr3tPs2j/CcQ+YKuu9ecKjYzMVFGimJ5NkXgEsl1zslg46+bCDJPWNtkdvuN3jnsf9cjr+O3JPlDAxX6CnZubjrDLRxJcEcWibrF3XtoBHMt7P0nMDqCnDHmbCJZFS1X/X00pz0Ma8yEvH9XdNUkighnzfc0qKg+ybgVI+O6NtOxAGvPh6fWsMS6SjmJlrvK60QHaNziCcFCoUTOZyMmXwcjwNYusPVIirONDobbbmgid2FzXUpGwOsH+m+AmbLDyKj75RGNUysF+VEmJWk+Pr9ZSspmJJBB9ER7x8kzqBJHd9brSZJuLmqjjx89TOf2z484AZnTPWVcXJBkA7NPFne6nHuLV0Dy4s5AY519aBJF9ND0KIZMxDrsKzDtrqWFa+/vRZan4=" # encrypted value of token

before_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=ON ..

script:
  - make clean
  # The wrapper is required by Sonar Cloud
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  - ctest

after_success:
  # Lcov coverage for Codecov
  - lcov --capture --directory . --output-file coverage.info
  # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash) -t 06fa5b08-3be1-480a-9af4-ffcec2672fa1 -f coverage.info || echo "Codecov did not collect coverage reports"
  # Generate gcov files for SonarCloud
  - LOCATION=gcovfiles
  - mkdir $LOCATION
  - find -name '*.c' -exec cp -t $LOCATION {} +
  - find -name '*.gcno' -exec cp -t $LOCATION {} +
  - find -name '*.gcda' -exec cp -t $LOCATION {} +
  - find $LOCATION -name '*.c' -exec gcov -bf {} \;
  # Report to SonarCloud
  - cd .. && sonar-scanner -Dproject.settings=.sonarcloud.properties

